#!/bin/bash
# Script will compare timing between fortran 90 and c programs

#if [ -z "$1" ]; then 
#        echo usage: $0 trials
#        exit
#fi
trials=$1
steps=200
Ninc=250


## Make the executables
make
brute=galaxy
bh=bhgalaxy

## Test timing for fortran case
echo '## N' $brute $bh  > speed_test.dat; 

for i in {1..12}
do
	    
    Np=0;
    Np=$(echo $Np $i $Ninc | awk '$1 = $2 * $3 {printf("%.13g\n",$1)}'|tail -1)
    echo 'Running' $brute $steps $Np
    time  (./$brute $steps $Np ) 2> tmp.txt;
    val=`grep user tmp.txt`;
    tn=`echo ${val:7:5}`; # Take out the numbers
    echo 'Time is' $tn 'seconds'


    Np=0;
    Np=$(echo $Np $i $Ninc | awk '$1 = $2 * $3 {printf("%.13g\n",$1)}'|tail -1)
    echo 'Running' $bh $steps $Np
    time  (./$bh $steps $Np ) 2> tmp.txt;
    val=`grep user tmp.txt`;
    tbh=`echo ${val:7:5}`; # Take out the numbers
    echo 'Time is' $tbh 'seconds'




    echo $Np $tn $tbh >> speed_test.dat
    
done

rm tmp.txt


#Notes: Gnuplot commands (for my use only)
#
#set term dumb feed 100 50
#set xlabel 'N-Particles'
#set ylabel 'Wall Time (sec)'
#set xrange [250:3000]
#plot 'speed_test.dat' u 1:2 w linespoints lt 1 pt 15 title 'Brute Force',\
# 'speed_test.dat' u 1:3 w linespoints lt 7 pt 15 title 'Barnes-Hut'